#!/usr/bin/env python3
"""Validate datapackage.json and keep SCHEMA.md generated from it."""
import argparse
import json
from pathlib import Path

from frictionless import Package

ROOT = Path(__file__).parent
DESCRIPTOR = ROOT / "data" / "datapackage.json"
SCHEMA_DOC = ROOT / "SCHEMA.md"


def render_schema(descriptor):
    lines = [
        "# Minihongo Content Schema\n",
        "Generated from `data/datapackage.json`. Do not edit this file by hand.\n",
    ]
    for resource in descriptor["resources"]:
        schema = resource.get("schema", {})
        lines += [f"## {resource['name']}\n", f"Source: `data/{resource['path']}`\n"]
        lines += ["| Column | Type | Constraints |", "|---|---|---|"]
        primary = set(schema.get("primaryKey", []))
        if isinstance(schema.get("primaryKey"), str):
            primary = {schema["primaryKey"]}
        for field in schema.get("fields", []):
            constraints = []
            if field["name"] in primary:
                constraints.append("primary key")
            if field.get("constraints", {}).get("required"):
                constraints.append("required")
            if field.get("constraints", {}).get("unique"):
                constraints.append("unique")
            lines.append(f"| `{field['name']}` | {field.get('type', 'any')} | {', '.join(constraints)} |")
        lines.append("")
        foreign_keys = schema.get("foreignKeys", [])
        if foreign_keys:
            lines.append("Foreign keys:")
            for key in foreign_keys:
                ref = key["reference"]
                lines.append(f"- `{key['fields']}` → `{ref['resource']}.{ref['fields']}`")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    report = Package(str(DESCRIPTOR)).validate()
    if not report.valid:
        for error in report.flatten(["rowNumber", "fieldName", "code", "message"]):
            print(" | ".join(str(value) for value in error))
        return 1
    descriptor = json.loads(DESCRIPTOR.read_text())
    expected = render_schema(descriptor)
    if args.write:
        SCHEMA_DOC.write_text(expected)
    elif not SCHEMA_DOC.exists() or SCHEMA_DOC.read_text() != expected:
        print("SCHEMA.md is stale; run: uv run validate_schema.py --write")
        return 1
    print("Schema and CSV integrity valid - OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
