// Run from the repository root: node scripts/export_echo.mjs
import {csv,sentence,stripFurigana,reading,hash,output} from './echo-export-lib.mjs';
const sourceURL='https://minihongo.com',attribution={name:'Minihongo',url:sourceURL,license:'CC BY-SA 4.0',licenseURL:'https://creativecommons.org/licenses/by-sa/4.0/'};
const words=[],records=[],grammar=[];
for(const file of ['words'])for(const row of csv(`data/${file}.csv`)){const target=row.minihongo||row.japanese,id=-parseInt(hash('minihongo:'+row.id).slice(0,12),16)-1;words.push({id,w:stripFurigana(target).replace(/\s+/g,''),r:row.reading||reading(target),en:[row.english],pos:['exp'],jlpt:'+',origin:'minihongo',sourceRow:row.id,category:row.category_id,definition:row.definition_minihongo||'',standardJapanese:row.japanese,sourceURL});const example=target,meaning=row.english;records.push(sentence(meaning,example,{project:'Minihongo',path:`data/${file}.csv`,row:row.id,attribution,starterVersion:2},{vocabulary:[id]}))}
for(const row of csv('data/grammar.csv'))grammar.push({id:'minihongo:'+row.id,title:row.japanese||stripFurigana(row.minihongo),level:'Mini Hongo',hint:row.english,explanation:row.explanation_english,explanationJapanese:row.explanation_japanese,origin:'minihongo',sourceURL});
const examples=csv('data/grammar_examples.csv');
for(const point of grammar){const candidates=examples.filter(row=>'minihongo:'+row.grammar_id===point.id).sort((a,b)=>stripFurigana(a.minihongo).length-stripFurigana(b.minihongo).length||Number(a.sort_order)-Number(b.sort_order));const row=candidates[0];if(!row)throw new Error('Missing grammar example: '+point.id);records.push(sentence(row.english,row.minihongo,{project:'Minihongo',path:'data/grammar_examples.csv',row:row.id,attribution,starterVersion:2},{grammar:[point.id]}))}
output('imports/jp-echo.json',records,{title:'Mini Hongo starter library',starterVersion:2,scope:'core-vocabulary-and-grammar',sourceURL,attribution,catalogues:{words,grammar},description:'Core vocabulary only: one word/gloss card per main vocabulary entry, and one short authored example per grammar point. No advanced vocabulary, compounds, expressions, texts or extra examples.'});
